// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lofi_backend.Database;

#nullable disable

namespace lofi_backend.Migrations
{
    [DbContext(typeof(LoFiDbContext))]
    [Migration("20260825134452_AddIsAdminToUserData")]
    partial class AddIsAdminToUserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("lofi_backend.Models.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Music");
                });

            modelBuilder.Entity("lofi_backend.Models.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = "playlist1",
                            Genre = 9,
                            Mood = 0,
                            Name = "Morning Focus"
                        },
                        new
                        {
                            Id = "playlist2",
                            Genre = 2,
                            Mood = 1,
                            Name = "Relax Evening"
                        },
                        new
                        {
                            Id = "playlist3",
                            Genre = 9,
                            Mood = 2,
                            Name = "Sleep Time"
                        });
                });

            modelBuilder.Entity("lofi_backend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 1, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Portfolio Website",
                            StartDate = new DateTime(2026, 1, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "test1"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "English Essay",
                            StartDate = new DateTime(2026, 6, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "test2"
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2026, 6, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sewing skirt",
                            StartDate = new DateTime(2026, 6, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "test3"
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2026, 6, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apply for job",
                            StartDate = new DateTime(2026, 6, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "test1"
                        });
                });

            modelBuilder.Entity("lofi_backend.Models.TaskTimer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Timers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2026, 1, 6, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2026, 1, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 3600,
                            IsActive = false,
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2026, 6, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2026, 6, 16, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Duration = 9000,
                            IsActive = false,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2026, 6, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2026, 6, 17, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Duration = 8100,
                            IsActive = false,
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2026, 6, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2026, 6, 22, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            Duration = 2700,
                            IsActive = false,
                            ProjectId = 4
                        });
                });

            modelBuilder.Entity("lofi_backend.Models.UserData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "test1",
                            DateOfBirth = new DateTime(1988, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "samuelgdukes@gmail.com",
                            FirstName = "Emma",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Thompson",
                            Username = "studyowl"
                        },
                        new
                        {
                            Id = "test2",
                            DateOfBirth = new DateTime(1995, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "matthew.p@example.com",
                            FirstName = "Matthew",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Painter",
                            Username = "lofilover"
                        },
                        new
                        {
                            Id = "test3",
                            DateOfBirth = new DateTime(2000, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "s.nguyen@example.com",
                            FirstName = "Sofia",
                            Gender = 2,
                            IsAdmin = false,
                            LastName = "Nguyen",
                            Username = "nightwave"
                        });
                });

            modelBuilder.Entity("lofi_backend.Models.Music", b =>
                {
                    b.HasOne("lofi_backend.Models.Playlist", null)
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId");
                });

            modelBuilder.Entity("lofi_backend.Models.Playlist", b =>
                {
                    b.HasOne("lofi_backend.Models.UserData", null)
                        .WithMany("Playlists")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("lofi_backend.Models.TaskTimer", b =>
                {
                    b.HasOne("lofi_backend.Models.Project", null)
                        .WithMany("Timers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lofi_backend.Models.Playlist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("lofi_backend.Models.Project", b =>
                {
                    b.Navigation("Timers");
                });

            modelBuilder.Entity("lofi_backend.Models.UserData", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
